import Navbar from 'components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import blogFetch from '../services/config'

export default function Home() {

  const [posts, setPosts] = useState([])

  const getPosts = async () => {
    try{
      const response = await blogFetch.get('/posts');
      const data = response.data
      setPosts(data)
    }
    catch (error) {
      console.log('erro de conexão Get:', error)
    }
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Página Inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <div className='pagina-inicial'>
          <h1>Posts mais recentes</h1>
          {posts.length === 0 ? (<p>Carregando...</p>) :
            (posts.map((post) => (
              <div className='post' key={post.id}>
                <h2>{post.title}</h2>
                <p>{post.body}</p>
                <Link href={`/posts/${post.id}`} className='geral-btn'>Ler mais</Link> //Não é funcional, era só para entender a ideia de rotas dinâmicas
              </div>
            ))
              )}
        </div>
      </main>
    </>
  )
}
