import Navbar from 'components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import { useState} from 'react'
import Router from 'next/router'
import blogFetch from '../services/config'

export default function NewPost() {
  // const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');

  const createPost = async (e) => {
    e.preventDefault();

    const post = { title, body, userId: 1 };

    await blogFetch.post('/posts', {
      body: post,
    })

    Router.push('/');
  };

  return (
    <>
      <Head>
        <title>Criar Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <div className="new-post">
          <h2>Inserir Novo Post</h2>
          <form onSubmit={(e) => createPost(e)}>
            <div className="form-control">
              <label htmlFor="title">Título:</label>
              <input type="text" name="title" id='title' placeholder='Digite o título' onChange={(e) => setTitle(e.target.value)}></input>
            </div>
            <div className="form-control">
              <label htmlFor="body">Conteúdo:</label>
              <textarea name="body" id="body" placeholder='Digite o conteúdo' onChange={(e) => setBody(e.target.value)}></textarea>
            </div>
            <input type='submit' value='Criar Post' className='geral-btn'></input>
          </form>
        </div>
      </main>
    </>
  )
}
