import Navbar from 'components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import { useState} from 'react'
import blogFetch from '../services/config'
import { useNavigate } from 'react-router-dom'

export default function NewPost() {
  // const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');

  const createPost = (e) => {
    e.preventDefault();

    console.log("teste");
  };

  return (
    <>
      <Head>
        <title>Criar Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <div className="new-post">
          <h2>Inserir Novo Post</h2>
          <form onSubmit={(e) => createPost(e)}>
            <div className="form-control">
              <label htmlFor="title">Título:</label>
              <input type="text" name="title" id='title' placeholder='Digite o título'></input>
            </div>
            <div className="form-control">
              <label htmlFor="body">Conteúdo:</label>
              <textarea name="body" id="body" placeholder='Digite o conteúdo'></textarea>
            </div>
            <input type='submit' value='Criar Post' className='geral-btn'></input>
          </form>
        </div>
      </main>
    </>
  )
}
